import './globals.css'
import {AuthProvider} from '@/context/AuthContext';
import Layout from '../components/Layout/Layout';

export const metadata = {
    title: 'DiscordLikeApp',
    description: 'A Discord-like real-time chat application',
}

const RootLayout = ({children}: { children: React.ReactNode }) => {
    return (
        <html lang="ja">
        <body>
        <AuthProvider>
            <Layout>{children}</Layout>
        </AuthProvider>
        </body>
        </html>
    );
};

export default RootLayout;

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
